### ISSUE TITLE
Version V11

### ISSUE THREAD

**Issue by YanKlInnomme** [tomski80/shiver#1]
Hello, 
First of all, thank you for your work. 
It's good, really good
Is a version for foundry VTT v11 planned?

**Comment by rollwight** [comment]
Not a developer, but I have found that if you change system.json to read;

    "verified": "11.299",
    "maximum": "11"

Instead of ;

    "verified": "10.286",
    "maximum": "10"

It will run fine. You will also need to lock your game system in foundry, otherwise it will just overwrite.

**Comment by YanKlInnomme** [comment]
Indeed, it's a solution that can help. But my question was more general, I was wondering if the game system was still maintained. The latest update is in alpha and dates back to 2022. **And as a result, due to a lack of updates, it no longer even appears in Foundry VTT's system installation library.** I think that's a real shame.

**Comment by tomski80** [comment]
I am extremely busy right now... I will update the system when I find some time. This is my hobby project. I would welcome requests and suggestions as well, so feel free to describe features you would like to see and I will see what I can do.

**Comment by tomski80** [comment]
I will re-apply to the foundry to add it to the lib soon.

**Comment by tomski80** [comment]
@YanKlInnomme @rollwight System has been updated to version 11.

**Comment by YanKlInnomme** [comment]
Great! Thanks a lot 🙏
